apiVersion: v1
kind: Secret
metadata:
  name: linkding-secret
  namespace: linkding
type: Opaque
data:
  LD_DB_PASSWORD: bGlua2RpbmdwYXNzd29yZA==
  postgres-password: cG9zdGdyZXMxMjM=
  postgres-user-password: bGlua2RpbmdwYXNzd29yZA==
